baseURL = "https://example.com"
languageCode = "zh-cn"
title = "TOC Page"
Paginate = 1000
googleAnalytics = ""
#theme = "toc-page"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  title = "TOC Page"
  description = "Table of Contents (TOC) Page is a minimal, single-page theme for Hugo."
  logo = "bookmark.png"
  copyright = "TOC Page Hugo - Yaney"
  copyrighturl = "https://github.com/y4ney"

[social]
  # You can add custom key value pairs here
  Github = "https://github.com/y4ney"
  Twitter = "https://x.com/Yaney_YangLi"
